name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: environment
      run: sudo apt-get install libdbus-1-dev

    - name: toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy

    - name: interface dependency
      run: sudo /usr/share/rust/.cargo/bin/cargo install dbus-codegen

    - name: generate interface
      run: dbus-codegen-rust < durst/interface.xml > durst/src/interface.rs

    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test

    # should be removed in the future, when generated code can be ignored
    - name: toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    # should be removed in the future, when generated code can be ignored
    - name: ignore lint for autogenerated files
      run: echo -e "#![allow(clippy::all)]\n$(cat durst/src/interface.rs)" > durst/src/interface.rs

    - name: lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
